#made for ec2 deployment
version: '3'
services:
  gateway:
    env_file:
      - .env
    build:
      context: ./gateway
    networks:
      - front
    ports:
      - "8080:80"
  backend:
    env_file:
      - .env
    build:
      context: ./backend
    networks:
      - front
  frontend:
    env_file:
      - .env
    build:
      context: ./frontend
    networks:
      - front
networks:
  front: