#made for ec2 deployment
version: '3'
services:
  gateway:
    env_file:
      - .env
    image: kolarz3/work-showcaser-gateway:latest
    networks:
      - front
    ports:
      - "8080:80"
  backend:
    env_file:
      - .env
    image: kolarz3/work-showcaser-backend:latest
    networks:
      - front
  frontend:
    env_file:
      - .env
    image: kolarz3/work-showcaser-frontend:latest
    networks:
      - front
networks:
  front: